backend:
  name: git-gateway
  branch: main

media_folder: "images"

collections:
  - name: "settings"
    label: "Website Content"
    files:
      - label: "Home Page"
        name: "home"
        file: "content.json"
        fields:
          - { label: "Main Title", name: "title", widget: "string" }
          - { label: "Main Text", name: "text", widget: "text" }
          - { label: "Main Image", name: "image", widget: "image" }